# azure-pipelines.yml
pool:
  vmImage: 'macOS 10.13'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '9.7.1'
  displayName: 'Install Node'
- script: yarn install
  displayName: 'Install dependencies'
- script: yarn run lint
  displayName: 'Run lint'
- script: yarn run test
  displayName: 'Run unit tests'
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: AppleDeveloperCertificate.p12
    certPwd: $(P12password)
    keychain: 'temp'
    deleteCert: true
  displayName: Install Apple Certificate
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'AppleProvisioningProfile.mobileprovision'
  displayName: 'Install Apple Provisioning Profile'